openapi: 3.2.0
info:
  title: Newline Platform Sandbox API
  version: 1.0.0
  description: Welcome!
servers:
- url: https://sandbox.newline53.com/api/v1
security:
- ApiKeyAuth: []
tags:
- name: Sandbox
  description: 'The Sandbox section provides tools to test and simulate interactions with the Newline API in a controlled environment.


    **Endpoints:**


    - POST Simulate a Transaction: POST /sandbox/mock_transactions'
paths:
  /sandbox/mock_transactions:
    parameters:
    - $ref: '#/paths/~1auth/parameters/0'
    post:
      tags:
      - Sandbox
      summary: Simulate a Transaction
      description: '> **Note** This endpoint is only available in Sandbox.


        Create a Transaction by simulating the attributes that would be expected from reading an actual transaction received from a third party system. The simulated Transaction will appear in the respective Transaction list after it is successfully processed.


        Transactions can be simulated against either a Synthetic Account, or a VRN that is created and mapped to a Synthetic Account.'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - type: object
                properties:
                  customer_uid:
                    type: string
                    example: uKxmLxUEiSj5h4M3
                    description: 'The uid of the customer for which to create the Transaction. Required except when `transaction_type` is `ach_return`.

                      '
                  transaction_type:
                    type: string
                    enum:
                    - wire
                    - instant_payment
                    - ach
                    - ach_return
                  transaction_uid:
                    type: string
                    example: 6DZvpWma5vLsfCcN
                    description: 'The Transaction UID value is required when the simulated transaction type is "ach_return". This is the transaction that newline will simulate the return for. The transaction supplied must be of type ''ACH''.

                      '
                  us_dollar_amount:
                    type: number
                    description: 'Positive value interpreted as a `credit`;

                      negative value interpreted as a `debit`.

                      Required for `transaction_type` of `wire`, `instant_payment`, and `ach`;

                      ignored when `transaction_type` is `ach_return`.'
                    example: 21.89
                  description:
                    type: string
                    minLength: 8
                    description: 'Additional information about this Mock Transaction; used as the Transaction description. When provided, a minimum of 8 characters is required.

                      '
                  synthetic_account_uid:
                    type: string
                    example: 4XkJnsfHsuqrxmeX
                    description: Optionally specifies the general Synthetic Account to be used for creating the transaction. If not passed, a random Synthetic Account belonging to the Customer will be used.
                  virtual_reference_number_uid:
                    type: string
                    example: tpowGE5fhRKVX3ge
                    description: 'Optional. If a VRN UID is supplied the simulated transaction will be associated with that VRN. The VRN UID must be in an active status. Only the following simulated transactions can have an associated VRN: wire credits, ACHs, or instant_payment.'
                  network:
                    type: string
                    enum:
                    - tch
                    - fednow
                    example: fednow
                    description: 'Optional. You may specify the network on which to simulate the transaction. If not specified, the default network `"tch"` will be used. Applicable for `transaction_type` of `instant_payment`.

                      '
                  counterparty_address:
                    description: 'Address of the business or individual who owns the external account. Applicable for `transaction_type` of `wire` or `instant_payment`.

                      '
                    oneOf:
                    - type: object
                      properties:
                        line1:
                          type:
                          - string
                          - 'null'
                          description: 'Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~

                            '
                          pattern: ^[^#@\$!"%&\*;<>\{\}_\^\\~\]\[]{0,35}$
                          example: 123 Abc St.
                        line2:
                          type:
                          - string
                          - 'null'
                          description: 'Optional 35 characters. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~

                            '
                          pattern: ^[^#@\$!"%&\*;<>\{\}_\^\\~\]\[]{0,35}$
                          example: Boring, Oregon 97009
                        line3:
                          type:
                          - string
                          - 'null'
                          description: 'Optional 32 characters. Note that this length is shorter than the other lines. Cannot contain \# @ $ ! " % & * ; < > { } [ ] _ ^ \ ~

                            '
                          pattern: ^[^#@\$!"%&\*;<>\{\}_\^\\~\]\[]{0,32}$
                          example: null
                        country:
                          allOf:
                          - type: string
                            description: '2 character ISO 3166 country code: https://www.iso.org/iso-3166-country-codes.html

                              '
                            maxLength: 2
                            minLength: 2
                          - type:
                            - string
                            - 'null'
                          - example: null
                    - type: object
                      properties:
                        street_number:
                          type: string
                          description: Building number for counterparty address. Alphanumeric only.
                          maxLength: 16
                          pattern: ^[a-zA-Z0-9]{1,16}$
                          example: 123abc
                        street1:
                          type: string
                          description: Street name for counterparty address
                          maxLength: 70
                          minLength: 3
                          pattern: '^[a-zA-Z0-9-. #/]{3,70}$'
                          example: Abc St.
                        street2:
                          type: string
                          description: Optional second line of street
                          maxLength: 70
                          pattern: '^[a-zA-Z0-9-. #/]{1,70}$'
                          example: Suite 4A
                        city:
                          type:
                          - string
                          - 'null'
                          description: Maximum 35 characters
                          maxLength: 35
                          pattern: ^[a-zA-Z-. /]{1,35}$
                          example: Chicago
                        state:
                          type:
                          - string
                          - 'null'
                          description: 2 characters. Must be a valid US state abbreviation.
                          pattern: ^\w{2}$
                          example: IL
                        postal_code:
                          type:
                          - string
                          - 'null'
                          description: 5-digit string. ZIP+4 is allowed.
                          pattern: ^\d{5}(-\d{4})?$
                          example: '60301'
                        country:
                          $ref: '#/paths/~1sandbox~1mock_transactions/post/requestBody/content/application~1json/schema/allOf/0/properties/counterparty_address/oneOf/0/properties/country'
                      required:
                      - street_number
                      - street1
                      - city
                      - state
                      - postal_code
                      - country
                  counterparty_name:
                    description: 'Name of the business or individual who owns the external account. Maximum 35 characters. Applicable for `transaction_type` of `wire` or `instant_payment`.

                      '
                    allOf:
                    - maxLength: 35
                      type: string
                      example: Marge's Roofing Inc
                  counterparty_bank_address:
                    description: 'Address of the financial institution where the external account is held. Applicable for `transaction_type` of `wire`.

                      '
                    allOf:
                    - $ref: '#/paths/~1sandbox~1mock_transactions/post/requestBody/content/application~1json/schema/allOf/0/properties/counterparty_address/oneOf/0'
                  counterparty_bank_name:
                    description: 'Name of the financial institution where the counterparty account is held. Maximum 35 characters. Applicable for `transaction_type` of `wire`.

                      '
                    allOf:
                    - maxLength: 35
                      type: string
                      example: East West Regional Bank
                  entry_description:
                    description: 'Description of the transaction. Applicable for `transaction_type` of `ach`.

                      '
                    allOf:
                    - type: string
                      minLength: 1
                      maxLength: 10
                      pattern: ^[a-zA-Z0-9 ]{1,10}$
                      example: ACH Entry
                  intermediary_bank_address:
                    description: 'Address of the intermediary bank, when applicable. Applicable for `transaction_type` of `wire`.

                      '
                    allOf:
                    - $ref: '#/paths/~1sandbox~1mock_transactions/post/requestBody/content/application~1json/schema/allOf/0/properties/counterparty_address/oneOf/0'
                  intermediary_bank_name:
                    description: 'Name of the intermediary bank, when applicable. Maximum 35 characters. Applicable for `transaction_type` of `wire`.

                      '
                    allOf:
                    - maxLength: 35
                      type: string
                      example: Fidelity Fiduciary Bank
                  intermediary_bank_routing_number:
                    description: 'The routing number associated with the intermediary bank involved in the wire transfer. Applicable for `transaction_type` of `wire`.

                      '
                    allOf:
                    - example: '923456789'
                      allOf:
                      - $ref: '#/paths/~1virtual_reference_numbers/post/requestBody/content/application~1json/schema/properties/routing_number/allOf/0'
                  memo:
                    description: 'A message transmitted to the recipient. Applicable for `transaction_type` of `instant_payment`.

                      '
                    allOf:
                    - description: 'A message transmitted to the recipient bank. Supports letters, numbers, and special characters: . !@#$%^&*'',/:;<=>?~`|[]{})(+=_- (max 140 characters).

                        '
                      allOf:
                      - type:
                        - string
                        - 'null'
                        example: 'Payment for invoice #123 @client'
                        maxLength: 140
                        pattern: ^[a-zA-Z0-9. !@#$%^&*',/:;<=>?~`|\[\]\{\})(+=_-]{0,140}$
                  wire_instructions:
                    description: 'Instructions for the recipient of the wire. Maximum 140 characters. Applicable for `transaction_type` of `wire`.

                      '
                    allOf:
                    - description: 'Additional details or instructions for the wire, issued to the recipient financial institution when the wire is executed.

                        '
                      allOf:
                      - type: string
                        maxLength: 140
                        example: Send ASAP
                  addenda:
                    allOf:
                    - type: string
                      description: 'Optional additional payment-related information, such as invoice numbers, originator/receiver information, payment instructions, etc. Up to 80 characters. Optional for all newline supported SEC codes other than TEL. Newline will reject the Transfer if an Addenda value is provided with SEC code TEL.

                        '
                      maxLength: 80
                      pattern: ^.{1,80}$
                  sec_code:
                    allOf:
                    - type: string
                      description: 'Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB. For more details, refer to our ACH guide''s [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.

                        '
                      enum:
                      - CCD
                      - CIE
                      - PPD
                      - TEL
                      - WEB
                      example: CIE
                  iat:
                    type:
                    - string
                    - 'null'
                    example: enabled
                    description: Optional. If the `iat` param is supplied on a mocked RDFI or ODFI ACH transaction, the transaction will have IAT details mocked accordingly.
              - type: object
                properties:
                  chips:
                    type:
                    - string
                    - 'null'
                    description: 'CHIPS number of the wire recipient. At most one of `chips`, `imad`, or `uetr` should be present.

                      '
                  imad:
                    type:
                    - string
                    - 'null'
                    description: 'FedWire IMAD number identifying a wire transaction. At most one of `chips`, `imad`, or `uetr` should be present.

                      '
                    example: 20220123ABCDEFGH123456
                  uetr:
                    type:
                    - string
                    - 'null'
                    description: 'Unique End to end Transaction Reference value from SWIFT for a wire transaction. At most one of `chips`, `imad`, or `uetr` should be present.

                      '
              required:
              - transaction_type
            examples:
              wire_mock_transaction_minimal:
                value:
                  customer_uid: kaxHFJnWvJxRJZxq
                  transaction_type: wire
                  us_dollar_amount: 21.89
              wire_mock_transaction:
                value:
                  customer_uid: kaxHFJnWvJxRJZxq
                  transaction_type: wire
                  us_dollar_amount: 21.89
                  counterparty_address:
                    line1: 123 Abc Ave
                    line2: San Francisco
                    line3: CA 94016
                    country: US
                  counterparty_name: Judith's Woodworks LLP
                  counterparty_bank_address:
                    line1: 345 Def Ave
                    line2: San Francisco
                    line3: CA 94016
                    country: US
                  counterparty_bank_name: Bank of Americana
                  imad: 20220123ABCDEFGH123456
                  synthetic_account_uid: 4XkJnsfHsuqrxmeX
                  wire_instructions: 'shipment #424 cedar owl dioramas'
                  virtual_reference_number_uid: tpowGE5fhRKVX3ge
              instant_payment_mock_transaction_minimal:
                value:
                  customer_uid: kaxHFJnWvJxRJZxq
                  transaction_type: instant_payment
                  us_dollar_amount: 21.89
              instant_payment_mock_transaction:
                value:
                  customer_uid: kaxHFJnWvJxRJZxq
                  counterparty_address:
                    line1: 123 Abc Ave
                    line2: San Francisco
                    line3: CA 94016
                    country: US
                  counterparty_name: Boryslav's Baking Co
                  description: Instant payments mock transaction
                  memo: weekly pumpernickel
                  transaction_type: instant_payment
                  us_dollar_amount: 21.89
                  virtual_reference_number_uid: tpowGE5fhRKVX3ge
              ach_mock_transaction:
                value:
                  customer_uid: kaxHFJnWvJxRJZxq
                  transaction_type: ach
                  us_dollar_amount: 21.89
                  synthetic_account_uid: 4XkJnsfHsuqrxmeX
                  sec_code: CCD
                  virtual_reference_number_uid: tpowGE5fhRKVX3ge
              ach_return_mock_transaction:
                value:
                  transaction_type: ach_return
                  transaction_uid: 6DZvpWma5vLsfCcN
      responses:
        '201':
          description: A success message is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: A mocked transaction has been successfully initiated.
                  uid:
                    type: string
                    description: 'The UID of the newly mocked Transaction.

                      '
                    example: mDBBkGGG4wJzg3QV
      operationId: postSandboxMockTransactions
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Access token signed with shared HMAC
x-explorer-enabled: false
