openapi: 3.2.0
info:
  title: Newline Platform Combined Transfers API
  version: 1.0.0
  description: Welcome!
servers:
- url: https://sandbox.newline53.com/api/v1
security:
- ApiKeyAuth: []
tags:
- name: Combined Transfers
  description: The Combined Transfers endpoint allows clients to create both a transfer and a counterparty in a single API call.
paths:
  /combined_transfers:
    parameters:
    - $ref: '#/paths/~1auth/parameters/0'
    get:
      tags:
      - Combined Transfers
      summary: List Combined Transfers
      description: Retrieves a list of Combined Transfers. These represent transactions where both a counterparty Synthetic Account and a Transfer were created in a single API call. You can filter results by status and other parameters.
      parameters:
      - $ref: '#/paths/~1pools/get/parameters/1'
      - $ref: '#/paths/~1pools/get/parameters/2'
      - $ref: '#/paths/~1transactions/get/parameters/15'
      - $ref: '#/paths/~1transactions/get/parameters/16'
      - $ref: '#/paths/~1transfers/get/parameters/1'
      - name: status
        in: query
        schema:
          type: string
          enum:
          - queued
          - pending
          - failed
          - completed
          example: completed
          description: 'Filter by status. Multiple values are allowed, e.g. `status[]=queued&status[]=pending`.

            '
      - name: synthetic_account_external_uid
        in: query
        schema:
          type: string
          example: client-generated-id
        description: 'A unique, immutable id provided by the Client. Multiple values are allowed e.g. `synthetic_account_external_uid[]=uKxmLxUEiSj5h4M3&synthetic_account_external_uid[]=y9reyPMNEWuuYSC1`.

          '
      - name: synthetic_account_pool_uid
        in: query
        schema:
          type: string
          example: wTSMX1GubP21ev2h
        description: 'Filter by Synthetic Account Pool. Multiple values are allowed, e.g. `synthetic_account_pool_uid[]=wTSMX1GubP21ev2h&synthetic_account_pool_uid[]=7UvkHn3Ss9AbWe2c`.

          '
      - name: synthetic_account_uid
        in: query
        schema:
          type: string
          example: 7UvkHn3Ss9AbWe2c
        description: 'Newline-generated unique id of the associated Synthetic Account. Multiple values are allowed, e.g. `synthetic_account_uid[]=wTSMX1GubP21ev2h&synthetic_account_uid[]=7UvkHn3Ss9AbWe2c`.

          '
      - name: transfer_customer_uid
        in: query
        schema:
          type: string
          example: wTSMX1GubP21ev2h
        description: 'Filter by Synthetic Transfer Customer. Multiple values are allowed, e.g. `transfer_customer_uid[]=wTSMX1GubP21ev2h&transfer_customer_uid[]=7UvkHn3Ss9AbWe2c`.

          '
      - name: transfer_external_uid
        in: query
        schema:
          type: string
          example: client-generated-id
        description: 'A unique, immutable id provided by the Client. Multiple values are allowed e.g. `transfer_external_uid[]=uKxmLxUEiSj5h4M3&transfer_external_uid[]=y9reyPMNEWuuYSC1`.

          '
      - name: transfer_uid
        in: query
        schema:
          type: string
          example: 7UvkHn3Ss9AbWe2c
        description: 'Newline-generated unique id of the associated Synthetic Transfer. Multiple values are allowed, e.g. `transfer_uid[]=wTSMX1GubP21ev2h&transfer_uid[]=7UvkHn3Ss9AbWe2c`.

          '
      responses:
        '200':
          description: A list of Combined Transfers is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/paths/~1pools/get/responses/200/content/application~1json/schema/allOf/0'
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - $ref: '#/paths/~1combined_transfers/post/responses/201/content/application~1json/schema'
              examples:
                combined_transfers_list:
                  value:
                    total_count: 4
                    count: 2
                    limit: 2
                    offset: 0
                    data:
                    - created_at: '2025-03-25T10:17:55.444Z'
                      status: completed
                      external_uid: 12345abcd
                      synthetic_account:
                        external_uid: abcd12345
                        name: Spinach Fund
                        pool_uid: axz9sbUgRVu5wqbw
                        routing_number: '04200031'
                        synthetic_account_type_uid: UyjH72G9KAhmbpNS
                        ach:
                          account_type: checking
                          counterparty_name: awesome counterparty
                        uid: dzc4FwjydgYAHpy9
                      transfer:
                        destination_synthetic_account_uid: azXvxqqcSsX9x9Yd
                        initiating_customer_uid: PszWYuoA3CSUvAaq
                        initiator_type: customer
                        usd_transfer_amount: '1.23'
                        ach:
                          effective_entry_date: '2025-03-27'
                          entry_description: Dividend Payment
                          originator_name: Big Bank Inc
                          company_id: COMPID1234
                          service_processing: SAMEDAY
                          sec_code: CCD
                          addenda: valuable extra info
                        uid: 87CwVJLxYnRsEHLS
                      uid: 1BGeBkH7tU7REZVx
                    - created_at: '2025-03-27T09:23:07.890Z'
                      status: queued
                      external_uid: null
                      synthetic_account:
                        uid: axz9sbUgRVu5wqbw
                      transfer:
                        initiating_customer_uid: PszWYuoA3CSUvAaq
                        initiator_type: customer
                        source_synthetic_account_uid: gfUHdwkR9kkEVxA4
                        usd_transfer_amount: '1.23'
                        wire:
                          intermediary_bank_name: Big Bank Inc
                          intermediary_bank_address:
                            line1: 123 Main St
                            line2: Brooklyn NY
                            country: US
                          intermediary_bank_routing_number: '123456789'
                          wire_transmitter:
                            name: Bunker LLC
                            line1: 456 Second St
                            line2: Queens NY
                            country: US
                            transmitter_identifier: '1234567890'
                        uid: null
                      uid: iLCATodsXhKPpPRv
        '403':
          description: Denied access to Combined Transfers
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1returns/get/responses/403/content/application~1json/schema'
              examples:
                combined_transfers_disabled:
                  value:
                    errors:
                    - code: 33004
                      title: Combined Transfers disabled
                      detail: Combined Transfer endpoints are not enabled for this program
                      occurred_at: '2025-03-27T09:23:07.890Z'
                    status: 403
        '422':
          description: Failed to retrieve Combined Transfers
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1returns/get/responses/403/content/application~1json/schema'
              examples:
                failed_to_retrieve_combined_transfers:
                  value:
                    errors:
                    - code: 33006
                      title: Failed to retrieve Combined Transfers
                      detail: An exception occurred while retrieving Combined Transfers
                      occurred_at: '2025-03-27T09:23:07.890Z'
                    status: 422
      operationId: getCombinedTransfers
      x-operation-id-source: derived
    post:
      tags:
      - Combined Transfers
      summary: Create a new Combined Transfer
      description: Creates a Combined Transfer by simultaneously creating a counterparty Synthetic Account and initiating a Transfer. This streamlines asset movement by reducing the number of steps required to set up and execute a transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                external_uid:
                  type: string
                  description: Optional client-supplied uid
                  example: YrfDrfVRgpPgnhF5
                synthetic_account:
                  allOf:
                  - $ref: '#/paths/~1synthetic_accounts/post/requestBody/content/application~1json/schema'
                  - type: object
                    description: 'Synthetic Account to be created or reused for a transfer. For more details on object structure, supported options and examples please refer to  [POST /synthetic_accounts](#tag/Synthetic-Accounts/paths/~1synthetic_accounts/post).

                      '
                transfer:
                  allOf:
                  - $ref: '#/paths/~1transfers/post/requestBody/content/application~1json/schema'
                  - type: object
                    description: 'Transfer details to initiate a transfer with. For more details on object structure, supported options and examples please refer to [POST /transfers](#tag/Transfers/paths/~1transfers/post). **NOTE:** Only source or destination synthetic account uid must be supplied for combined transfer, `synthetic_account` from the request will be used as the other party.

                      '
              required:
              - synthetic_account
              - transfer
            examples:
              ach_transfer_to_new_account:
                value:
                  synthetic_account:
                    account_number: '1234567890'
                    external_uid: abcd12345
                    name: Spinach Fund
                    pool_uid: axz9sbUgRVu5wqbw
                    routing_number: '04200031'
                    synthetic_account_type_uid: UyjH72G9KAhmbpNS
                    ach:
                      account_type: checking
                      counterparty_name: awesome counterparty
                  transfer:
                    destination_synthetic_account_uid: beHyJNeBU65Xv8LK
                    initiating_customer_uid: axz9sbUgRVu5wqbw
                    usd_transfer_amount: '12.34'
                    initiator_type: customer
                    ach:
                      destination_synthetic_account_uid: azXvxqqcSsX9x9Yd
                      initiating_customer_uid: PszWYuoA3CSUvAaq
                      initiator_type: customer
                      usd_transfer_amount: '1.23'
                      ach:
                        effective_entry_date: '2025-03-27'
                        entry_description: Dividend Payment
                        originator_name: Big Bank Inc
                        company_id: COMPID1234
                        service_processing: SAMEDAY
                        sec_code: CCD
                        addenda: valuable extra info
                      uid: 87CwVJLxYnRsEHLS
              ach_transfer_to_existing_account:
                value:
                  synthetic_account:
                    uid: dzc4FwjydgYAHpy9
                  transfer:
                    destination_synthetic_account_uid: beHyJNeBU65Xv8LK
                    initiating_customer_uid: axz9sbUgRVu5wqbw
                    usd_transfer_amount: '12.34'
                    initiator_type: customer
                    ach:
                      destination_synthetic_account_uid: azXvxqqcSsX9x9Yd
                      initiating_customer_uid: PszWYuoA3CSUvAaq
                      initiator_type: customer
                      usd_transfer_amount: '1.23'
                      ach:
                        effective_entry_date: '2025-03-27'
                        entry_description: Dividend Payment
                        originator_name: Big Bank Inc
                        company_id: COMPID1234
                        service_processing: SAMEDAY
                        sec_code: CCD
                        addenda: valuable extra info
                      uid: 87CwVJLxYnRsEHLS
              instant_payment_transfer_to_new_account:
                value:
                  synthetic_account:
                    account_number: '1234567890'
                    external_uid: abcd12345
                    name: Spinach Fund
                    pool_uid: axz9sbUgRVu5wqbw
                    routing_number: '04200031'
                    synthetic_account_type_uid: UyjH72G9KAhmbpNS
                    instant_payment:
                      email: address@domain.com
                      counterparty_name: awesome counterparty
                      phone: '2121112233'
                      counterparty_address:
                        street_number: 123
                        street1: Main street
                        city: Brooklyn
                        state: IA
                        postal_code: 12345-6789
                        country: US
                  transfer:
                    destination_synthetic_account_uid: beHyJNeBU65Xv8LK
                    initiating_customer_uid: axz9sbUgRVu5wqbw
                    usd_transfer_amount: '12.34'
                    initiator_type: customer
                    instant_payment:
                      instant_payment_transmitter:
                        name: Royalty Asset Management
                        transmitter_identifier: '123456789'
                        street_number: 123
                        street1: Abc St.
                        city: Boring
                        state: OR
                        postal_code: 97009
                      memo: To unfreeze the prince's assets
              instant_payment_transfer_to_existing_account:
                value:
                  synthetic_account:
                    uid: dzc4FwjydgYAHpy9
                  transfer:
                    destination_synthetic_account_uid: beHyJNeBU65Xv8LK
                    initiating_customer_uid: axz9sbUgRVu5wqbw
                    usd_transfer_amount: '12.34'
                    initiator_type: customer
                    instant_payment:
                      instant_payment_transmitter:
                        name: Royalty Asset Management
                        transmitter_identifier: '123456789'
                        street_number: 123
                        street1: Abc St.
                        city: Boring
                        state: OR
                        postal_code: 97009
                      memo: To unfreeze the prince's assets
              wire_transfer_to_new_account:
                value:
                  synthetic_account:
                    account_number: '1234567890'
                    external_uid: abcd12345
                    name: Spinach Fund
                    pool_uid: axz9sbUgRVu5wqbw
                    routing_number: '04200031'
                    synthetic_account_type_uid: UyjH72G9KAhmbpNS
                    wire:
                      counterparty_name: Awesome Counterparty
                      counterparty_bank_name: Biggest Bank Inc
                  transfer:
                    destination_synthetic_account_uid: beHyJNeBU65Xv8LK
                    initiating_customer_uid: axz9sbUgRVu5wqbw
                    usd_transfer_amount: '12.34'
                    initiator_type: customer
                    wire:
                      intermediary_bank_name: Big Bank Inc
                      intermediary_bank_address:
                        line1: 123 Main St
                        line2: Brooklyn NY
                        country: US
                      intermediary_bank_routing_number: '123456789'
                      wire_transmitter:
                        name: Bunker LLC
                        line1: 456 Second St
                        line2: Queens NY
                        country: US
                        transmitter_identifier: '1234567890'
              wire_transfer_to_existing_account:
                value:
                  synthetic_account:
                    uid: dzc4FwjydgYAHpy9
                  transfer:
                    destination_synthetic_account_uid: beHyJNeBU65Xv8LK
                    initiating_customer_uid: axz9sbUgRVu5wqbw
                    usd_transfer_amount: '12.34'
                    initiator_type: customer
                    wire:
                      intermediary_bank_name: Big Bank Inc
                      intermediary_bank_address:
                        line1: 123 Main St
                        line2: Brooklyn NY
                        country: US
                      intermediary_bank_routing_number: '123456789'
                      wire_transmitter:
                        name: Bunker LLC
                        line1: 456 Second St
                        line2: Queens NY
                        country: US
                        transmitter_identifier: '1234567890'
      responses:
        '201':
          description: A single Combined Transfer is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                type: object
                properties:
                  created_at:
                    type: string
                    description: Timestamp of when the combined_transfer was created
                    example: '2025-03-27T09:23:07.890Z'
                  errors:
                    type: array
                    description: 'A collection of errors that occured during synthetic account and/or transfer creation. Only displayed if errors were detected.

                      '
                    items:
                      $ref: '#/paths/~1returns/get/responses/403/content/application~1json/schema/properties/errors/items'
                    example:
                    - code: 33005
                      title: Could not continue Combined Transfer
                      detail: An exception occurred while continuing a Combined Transfer
                      occurred_at: '2025-03-27T09:23:07.890Z'
                  external_uid:
                    $ref: '#/paths/~1combined_transfers/post/requestBody/content/application~1json/schema/properties/external_uid'
                  status:
                    description: The combined transfer's status
                    type: string
                    example: pending
                    enum:
                    - queued
                    - pending
                    - failed
                    - completed
                  synthetic_account:
                    type: object
                    description: 'Parameters provided at time of creation. UID field will get populated once synthetic account has been successfully created, unless uid value was supplied at creation time.

                      '
                  transfer:
                    type: object
                    description: 'Parameters provided at time of creation. UID field will get populated once transfer has been successfully initiated.

                      '
                  uid:
                    type: string
                    description: Unique identifier for the Combined Transfer
                    example: dYTG8WAWAh5UyvY7
              examples:
                queued:
                  value:
                    created_at: '2025-03-27T09:23:07.890Z'
                    status: queued
                    external_uid: null
                    synthetic_account:
                      external_uid: abcd12345
                      name: Spinach Fund
                      pool_uid: axz9sbUgRVu5wqbw
                      routing_number: '04200031'
                      synthetic_account_type_uid: UyjH72G9KAhmbpNS
                      wire:
                        counterparty_name: Awesome Counterparty
                        counterparty_bank_name: Biggest Bank Inc
                      uid: null
                    transfer:
                      destination_synthetic_account_uid: azXvxqqcSsX9x9Yd
                      initiating_customer_uid: PszWYuoA3CSUvAaq
                      initiator_type: customer
                      source_synthetic_account_uid: gfUHdwkR9kkEVxA4
                      usd_transfer_amount: '1.23'
                      wire:
                        intermediary_bank_name: Big Bank Inc
                        intermediary_bank_address:
                          line1: 123 Main St
                          line2: Brooklyn NY
                          country: US
                        intermediary_bank_routing_number: '123456789'
                        wire_transmitter:
                          name: Bunker LLC
                          line1: 456 Second St
                          line2: Queens NY
                          country: US
                          transmitter_identifier: '1234567890'
                      uid: null
                    uid: iLCATodsXhKPpPRv
        '403':
          description: Denied access to Combined Transfers
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1returns/get/responses/403/content/application~1json/schema'
              examples:
                combined_transfers_disabled:
                  $ref: '#/paths/~1combined_transfers/get/responses/403/content/application~1json/examples/combined_transfers_disabled'
        '422':
          description: Creation Error
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1returns/get/responses/403/content/application~1json/schema'
              examples:
                combined_transfer_creation_error:
                  value:
                    errors:
                    - code: 33001
                      title: Could not create Combined Transfer
                      detail: An exception occurred while creating a Combined Transfer
                      occurred_at: '2025-03-27T09:23:07.890Z'
                    status: 422
                combined_transfer_external_uid_taken:
                  value:
                    errors:
                    - code: 33007
                      title: Combined Transfer external uid is already taken
                      detail: Combined Transfer external uid must be unique
                      occurred_at: '2025-03-27T09:23:07.890Z'
                    status: 422
      operationId: postCombinedTransfers
      x-operation-id-source: derived
  /combined_transfers/{uid}:
    parameters:
    - $ref: '#/paths/~1auth/parameters/0'
    - $ref: '#/paths/~1pools~1%7Buid%7D/parameters/1'
    get:
      tags:
      - Combined Transfers
      summary: Get a single Combined Transfer
      description: Retrieves details about a specific Combined Transfer, including the status, participating accounts, and associated metadata. Statuses include `queued`, `pending`, `failed`, and `completed`.
      responses:
        '200':
          description: A single Combined Transfer is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1combined_transfers/post/responses/201/content/application~1json/schema'
              examples:
                queued:
                  $ref: '#/paths/~1combined_transfers/post/responses/201/content/application~1json/examples/queued'
                pending:
                  value:
                    created_at: '2025-03-27T09:23:07.890Z'
                    status: pending
                    external_uid: null
                    synthetic_account:
                      external_uid: abcd12345
                      name: Spinach Fund
                      pool_uid: axz9sbUgRVu5wqbw
                      routing_number: '04200031'
                      synthetic_account_type_uid: UyjH72G9KAhmbpNS
                      wire:
                        counterparty_name: Awesome Counterparty
                        counterparty_bank_name: Biggest Bank Inc
                      uid: null
                    transfer:
                      destination_synthetic_account_uid: azXvxqqcSsX9x9Yd
                      initiating_customer_uid: PszWYuoA3CSUvAaq
                      initiator_type: customer
                      source_synthetic_account_uid: gfUHdwkR9kkEVxA4
                      usd_transfer_amount: '1.23'
                      wire:
                        intermediary_bank_name: Big Bank Inc
                        intermediary_bank_address:
                          line1: 123 Main St
                          line2: Brooklyn NY
                          country: US
                        intermediary_bank_routing_number: '123456789'
                        wire_transmitter:
                          name: Bunker LLC
                          line1: 456 Second St
                          line2: Queens NY
                          country: US
                          transmitter_identifier: '1234567890'
                      uid: null
                    uid: iLCATodsXhKPpPRv
                failed:
                  value:
                    created_at: '2025-03-27T09:23:07.890Z'
                    status: failed
                    errors:
                    - code: 33005
                      title: Could not continue Combined Transfer
                      detail: An exception occurred while continuing a Combined Transfer
                      occurred_at: '2025-03-27T09:23:07.890Z'
                    external_uid: null
                    synthetic_account:
                      external_uid: abcd12345
                      name: Spinach Fund
                      pool_uid: axz9sbUgRVu5wqbw
                      routing_number: '04200031'
                      synthetic_account_type_uid: UyjH72G9KAhmbpNS
                      wire:
                        counterparty_name: Awesome Counterparty
                        counterparty_bank_name: Biggest Bank Inc
                      uid: null
                    transfer:
                      destination_synthetic_account_uid: azXvxqqcSsX9x9Yd
                      initiating_customer_uid: PszWYuoA3CSUvAaq
                      initiator_type: customer
                      source_synthetic_account_uid: gfUHdwkR9kkEVxA4
                      usd_transfer_amount: '1.23'
                      wire:
                        intermediary_bank_name: Big Bank Inc
                        intermediary_bank_address:
                          line1: 123 Main St
                          line2: Brooklyn NY
                          country: US
                        intermediary_bank_routing_number: '123456789'
                        wire_transmitter:
                          name: Bunker LLC
                          line1: 456 Second St
                          line2: Queens NY
                          country: US
                          transmitter_identifier: '1234567890'
                      uid: null
                    uid: iLCATodsXhKPpPRv
                completed:
                  value:
                    created_at: '2025-03-27T09:23:07.890Z'
                    status: completed
                    external_uid: null
                    synthetic_account:
                      external_uid: abcd12345
                      name: Spinach Fund
                      pool_uid: axz9sbUgRVu5wqbw
                      routing_number: '04200031'
                      synthetic_account_type_uid: UyjH72G9KAhmbpNS
                      wire:
                        counterparty_name: Awesome Counterparty
                        counterparty_bank_name: Biggest Bank Inc
                      uid: dzc4FwjydgYAHpy9
                    transfer:
                      destination_synthetic_account_uid: azXvxqqcSsX9x9Yd
                      initiating_customer_uid: PszWYuoA3CSUvAaq
                      initiator_type: customer
                      source_synthetic_account_uid: gfUHdwkR9kkEVxA4
                      usd_transfer_amount: '1.23'
                      wire:
                        intermediary_bank_name: Big Bank Inc
                        intermediary_bank_address:
                          line1: 123 Main St
                          line2: Brooklyn NY
                          country: US
                        intermediary_bank_routing_number: '123456789'
                        wire_transmitter:
                          name: Bunker LLC
                          line1: 456 Second St
                          line2: Queens NY
                          country: US
                          transmitter_identifier: '1234567890'
                      uid: 87CwVJLxYnRsEHLS
                    uid: iLCATodsXhKPpPRv
        '403':
          description: Denied access to Combined Transfers
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1returns/get/responses/403/content/application~1json/schema'
              examples:
                combined_transfers_disabled:
                  $ref: '#/paths/~1combined_transfers/get/responses/403/content/application~1json/examples/combined_transfers_disabled'
        '404':
          description: The Combined Transfer is not found
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1returns/get/responses/403/content/application~1json/schema'
              examples:
                unknown_combined_transfer:
                  value:
                    errors:
                    - code: 33000
                      title: Unknown combined transfer
                      detail: Could not find combined transfer
                      occurred_at: '2025-03-27T09:23:07.890Z'
                    status: 404
      operationId: getCombinedTransfersByUid
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Access token signed with shared HMAC
x-explorer-enabled: false
