openapi: 3.2.0
info:
  title: Newline Platform Customers API
  version: 1.0.0
  description: Welcome!
servers:
- url: https://sandbox.newline53.com/api/v1
security:
- ApiKeyAuth: []
tags:
- name: Customers
  description: The Customers section provides details on managing end-user accounts.
paths:
  /customers:
    parameters:
    - $ref: '#/paths/~1auth/parameters/0'
    get:
      tags:
      - Customers
      summary: Get a list of Customers
      description: 'Retrieves a list of Customers filtered by the given parameters. Filter parameters are not case sensitive, but will only return exact matches.


        Multiple filter parameters can be provided at once, but a result will not be returned unless there are exact matches for all submitted parameters. As an example: submitting `first_name=Olive&last_name=Oyl` would match exactly "Olive Oyl" but NOT "Olive Boyl" or "Oliver Oyl".


        The list endpoint will not include sensitive Customer data such as address or DOB. This can only be retrieved by viewing a specific Customer record. By default we do not display Customers in the `initiated` status, as Customers in this status have not completed onboarding. To cause Customers with this status to be included in the list you must provide the `include_initiated=true` parameter.'
      parameters:
      - name: uid
        in: query
        schema:
          type: string
          example: uKxmLxUEiSj5h4M3
        description: 'Filter by Customer. Multiple values are allowed e.g. `uid[]=uKxmLxUEiSj5h4M3&uid[]=y9reyPMNEWuuYSC1`.

          '
      - name: status
        in: query
        schema:
          type: string
          enum:
          - initiated
          - queued
          - identity_verified
          - active
          - manual_review
          - rejected
          - pending_archival
          - archived
          - under_review
        description: 'Filter by onboarding status. Please note that the `initiated` enum value will not be respected unless the `include_initiated=true` parameter is also provided. Multiple values are allowed e.g. `status[]=queued&status[]=active`.

          '
      - name: include_initiated
        in: query
        schema:
          type: boolean
          example: true
        description: 'By default, Customers in `initiated` status are not shown, even if the `status=initiated` parameter is provided. In order for Customers with status `initiated` to appear in search results, parameters must include `include_initiated=true`

          '
      - name: kyc_status
        in: query
        schema:
          type: string
          enum:
          - approved
          - denied
          - documents_provided
          - documents_rejected
          - manual_review
          - pending_id_documents
          - pending_poa_documents
          - pending_idandpoa_documents
          - retake_images
          - pre_verified
        description: Filter by KYC status. Multiple values are allowed e.g. `kyc_status[]=approved&kyc_status[]=under_review`.
      - name: customer_type
        in: query
        schema:
          type: string
          example: primary
          enum:
          - primary
          - secondary
          - sole_proprietor
        description: 'Only return Customers with a customer type matching exactly what is submitted. Multiple values are allowed e.g. `customer_type[]=primary&customer_type[]=secondary`.

          '
      - name: first_name
        in: query
        schema:
          type: string
          example: Olive
        description: 'Only return Customers with a first name matching exactly what is submitted. Multiple values are allowed e.g. `first_name[]=Olive&first_name[]=Jack`.

          '
      - name: last_name
        in: query
        schema:
          type: string
          example: Oyl
        description: 'Only return Customers with a last name matching exactly what is submitted. Multiple values are allowed e.g. `last_name[]=Oyl&last_name[]=Hammon`.

          '
      - name: email
        in: query
        schema:
          type: string
          example: olive.oyl@popeyes.com
        description: 'Only return Customers with an email address matching exactly what is submitted. Multiple values are allowed e.g. `email[]=olive.oyl@popeyes.com&email[]=olive.oyl2@gmail.com`.

          '
      - name: locked
        in: query
        schema:
          type: boolean
          example: false
        description: Only return locked Customers if `true` and only return unlocked Customers if `false`
      - name: program_uid
        in: query
        schema:
          type: string
          example: pQtTCSXz57fuefzp
        description: 'Only return Customers belonging to the submitted Program. Multiple values are allowed e.g. `program_uid[]=pQtTCSXz57fuefzp&program_uid[]=oPsSBRWy46etdeyo`.

          '
      - name: business_name
        in: query
        schema:
          type: string
          example: Business inc
        description: 'Only return Customers with a business name at least partially matching what is submitted. Exact matches will be sorted first.

          '
      - $ref: '#/paths/~1transfers/get/parameters/1'
      - $ref: '#/paths/~1transfers/get/parameters/2'
      - $ref: '#/paths/~1pools/get/parameters/1'
      - $ref: '#/paths/~1pools/get/parameters/2'
      - name: sort
        in: query
        schema:
          type: string
          enum:
          - activated_at_asc
          - activated_at_desc
          - first_name_asc
          - first_name_desc
          - last_name_asc
          - last_name_desc
          - email_asc
          - email_desc
      responses:
        '200':
          description: A list of Customers is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/paths/~1pools/get/responses/200/content/application~1json/schema/allOf/0'
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        allOf:
                        - $ref: '#/paths/~1transfers/post/requestBody/content/application~1json/schema/allOf/0'
                        - $ref: '#/paths/~1customers/post/responses/201/content/application~1json/schema/allOf/1'
                        - type: object
                          properties:
                            details:
                              $ref: '#/paths/~1customers~1%7Buid%7D/put/requestBody/content/application~1json/schema/properties/details/allOf/0'
              examples:
                customer_list:
                  value:
                    total_count: 10
                    count: 2
                    limit: 2
                    offset: 0
                    data:
                    - activated_at: '2019-10-14T03:21:53.301Z'
                      created_at: '2019-10-13T03:21:53.301Z'
                      customer_type: primary
                      details:
                        first_name: Cletus
                        middle_name: Nathanial
                        last_name: Borer
                        suffix: null
                        phone: '4863567322'
                      email: Cletus_Borer@hotmail.com
                      external_uid: 0396a8f6-37d5-4386-bb63-86987ac88132
                      client_verified: false
                      kyc_status: pending_id_documents
                      lock_reason: null
                      locked_at: null
                      pool_uids:
                      - 1rNd8vRVa4GX84vi
                      primary_customer_uid: null
                      program_uid: Sw9DjTGJq5L1ctZN
                      secondary_customer_uids: []
                      status: manual_review
                      total_balance: '0'
                      uid: uKxmLxUEiSj5h4M3
                      archived_at: null
                    - activated_at: '2021-10-13T03:22:53.301Z'
                      created_at: '2021-10-12T03:22:53.103Z'
                      customer_type: sole_proprietor
                      details:
                        first_name: Billy
                        middle_name: Bob
                        last_name: Beansmith
                        business_name: Billy Bob's Beans
                        suffix: null
                        phone: '4863567323'
                      email: billybob@beansmith.name
                      external_uid: 0396a8f7-37d5-4386-bb63-86987ac8813c
                      client_verified: false
                      kyc_status: approved
                      lock_reason: null
                      locked_at: null
                      pool_uids:
                      - 2rNd8vRVa4GX84vh
                      primary_customer_uid: null
                      program_uid: Tw9DjTGJq5L1ctZ1
                      secondary_customer_uids:
                      - 6gSxo29K4Q3CLseL
                      - Hu1B6KMNR8juYwb5
                      status: active
                      total_balance: '10'
                      uid: 3KxmLxUEiSj5h4Mu
                      archived_at: null
                    - activated_at: '2019-10-16T03:21:53.301Z'
                      created_at: '2019-10-14T03:21:53.301Z'
                      customer_type: primary
                      details:
                        first_name: Lemuel
                        middle_name: Brian
                        last_name: Olson
                        suffix: Jr.
                        phone: '6728868534'
                      email: Lemuel95@hotmail.com
                      external_uid: 844b9579-3a5d-47f0-88b2-305548974479
                      client_verified: false
                      kyc_status: approved
                      lock_reason: Customer Reported Fraud
                      locked_at: '2020-03-30T15:15:06Z'
                      pool_uids:
                      - o5oZEkpMte8zGJmR
                      - 96E5UzZyTXyJmFpm
                      primary_customer_uid: null
                      program_uid: Sw9DjTGJq5L1ctZN
                      secondary_customer_uids: []
                      status: active
                      total_balance: '-606.4'
                      uid: y9reyPMNEWuuYSC1
                      archived_at: null
      operationId: getCustomers
      x-operation-id-source: derived
    post:
      tags:
      - Customers
      summary: Create a new Customer
      description: 'This endpoint is used to initialize a new Customer. All request body data is optional unless otherwise specified. For customer types other than `primary`, `customer_type` must be specified.


        The `customer_type` cannot be changed after the customer is created. Customer details accepted by Adjust Customer Data can be sent in this request if desired. See Adjust Customer Data for an example with all customer details provided.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
              - type: object
                properties:
                  customer_type:
                    type: string
                    enum:
                    - primary
                    - secondary
                    - sole_proprietor
                    description: 'The type of Customer. Defaults to `primary`.

                      '
                  primary_customer_uid:
                    type:
                    - string
                    - 'null'
                    description: 'The UID of the Primary Customer with whom this Secondary Customer will be affiliated. Required for and only applicable to requests with customer_type `secondary`. Cannot be updated later from the initial value.

                      '
                  client_verified:
                    type:
                    - boolean
                    - 'null'
                    description: 'Indicates whether the client has already performed identity verification of the Customer. The client''s Program must be configured to accept this value. All Customers in a Program configured for this value must submit true in this field to complete onboarding. This value defaults to `false`.

                      '
              - $ref: '#/paths/~1customers~1%7Buid%7D/put/requestBody/content/application~1json/schema'
            examples:
              primary:
                summary: create primary
                value:
                  external_uid: client-generated-42
                  email: tomas@example.com
              secondary:
                summary: create secondary
                value:
                  external_uid: client-generated-42
                  email: tomas@example.com
                  customer_type: secondary
                  primary_customer_uid: dc6PApa2nn9K3jwL
              primary-empty:
                summary: create primary (empty body)
                value: {}
      responses:
        '201':
          description: A newly created Customer is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/paths/~1transfers/post/requestBody/content/application~1json/schema/allOf/0'
                - type: object
                  properties:
                    activated_at:
                      type: string
                      format: date-time
                      readOnly: true
                      example: '2019-10-15T03:21:53.301Z'
                      description: The date and time at which this Customer was activated.
                    created_at:
                      type: string
                      format: date-time
                      readOnly: true
                      example: '2019-10-14T03:21:53.301Z'
                    customer_type:
                      type: string
                      enum:
                      - primary
                      - secondary
                      - sole_proprietor
                      - sub_ledger
                      description: 'The type of Customer

                        '
                      example: primary
                    email:
                      type: string
                      description: Email of the Customer
                      example: olive.oyl@newline53.com
                    client_verified:
                      type: boolean
                      description: Indicates whether or not the client is responsible for identity verification of this Customer. If true, the `kyc_status` will be "pre_verified".
                      example: false
                    kyc_status:
                      type:
                      - string
                      - 'null'
                      description: 'A value indicating the state of KYC/AML evaluation.

                        '
                      enum:
                      - manual_review
                      - approved
                      - denied
                      - pending_id_documents
                      - pending_poa_documents
                      - pending_idandpoa_documents
                      - documents_provided
                      - documents_rejected
                      - retake_images
                      - pre_verified
                      readOnly: true
                    kyc_status_reasons:
                      type:
                      - array
                      - 'null'
                      description: A list of reasons for the current `kyc_status`.
                      items:
                        type: string
                        enum:
                        - Approved
                        - Valid Documents Provided
                        - Archived due to application inactivity
                        - Further review required
                        - Minor (age < 18 years)
                        - Invalid Documents submitted multiple times
                        - Minimum requirements to open an account were not met
                        - Invalid documents
                        - Incorrect document provided for ID document
                        - Expired ID
                        - Illegible ID document
                        - Incorrect document provided for POA document
                        - Invalid POA provided
                        - Illegible POA document
                      readOnly: true
                    lock_reason:
                      type:
                      - string
                      - 'null'
                      readOnly: true
                      example: null
                      description: 'The lock reason provided by the Client, an admin User, or the system at the time the Customer was locked. This field will be null if and only if the `locked_at` is null.

                        '
                    locked_at:
                      type:
                      - string
                      - 'null'
                      format: date-time
                      readOnly: true
                      example: null
                      description: 'The date and time when the Customer was locked. This field will be null if and only if the `lock_reason` is null.

                        '
                    pii_confirmed_at:
                      type: string
                      format: date-time
                      readOnly: true
                      example: '2020-10-14T03:21:53.301Z'
                      description: 'The date and time when the Customer''s PII was last confirmed to be accurate

                        '
                    pool_uids:
                      type: array
                      description: A list of uids referring to Pools belonging to this Customer.
                      items:
                        type: string
                        example: HiuQZJNjCd79LLYq, NoPJB9g9ZQTh5qMv
                      readOnly: true
                    primary_customer_uid:
                      type:
                      - string
                      - 'null'
                      description: The UID of the primary Customer. Null unless the customer type is `secondary`.
                      readOnly: true
                      example: null
                    profile_responses:
                      type: array
                      description: A list of Profile Responses submitted by the Customer
                      items:
                        type: object
                        properties:
                          profile_requirement:
                            type: string
                            description: A statement that requires a response in order to onboard a Customer for a Product
                            example: Please provide your approximate annual income in USD.
                          profile_response:
                            type: string
                            description: The Customer's response to the Profile Requirement as a single string value.
                            example: Profile response
                          profile_requirement_uid:
                            type: string
                            description: A UID referring to the Profile Requirement
                            example: ptRLF7nQvy8VoqM1
                      readOnly: true
                    program_uid:
                      type: string
                      description: A UID referring to the program this customer belongs to
                      example: kaxHFJnWvJxRJZxr
                      readOnly: true
                    secondary_customer_uids:
                      type:
                      - array
                      - 'null'
                      description: The UIDs of secondary Customers. Null unless the customer type is `primary`.
                      items:
                        type: string
                        example: 464QyebpxbBNrGkX
                      readOnly: true
                    status:
                      type: string
                      description: 'A value indicating the overall state of this Customer.

                        '
                      enum:
                      - initiated
                      - queued
                      - identity_verified
                      - active
                      - manual_review
                      - rejected
                      - pending_archival
                      - archived
                      - under_review
                      readOnly: true
                    total_balance:
                      type: string
                      description: Total asset owned by the customer in US dollars
                      readOnly: true
                      example: '12345.67'
                    archived_at:
                      type:
                      - string
                      - 'null'
                      format: date-time
                      readOnly: true
                      example: null
                      description: 'If the Customer''s status is `archived` this will have the time at which they were archived.

                        '
                - type: object
                  properties:
                    details:
                      $ref: '#/paths/~1customers~1%7Buid%7D/put/requestBody/content/application~1json/schema/properties/details'
              examples:
                empty_customer:
                  value:
                    activated_at: '2019-10-16T03:21:53.301Z'
                    created_at: '2019-10-15T03:21:53.301Z'
                    customer_type: primary
                    details:
                      first_name: null
                      middle_name: null
                      last_name: null
                      suffix: null
                      phone: null
                    email: Cletus_Borer@hotmail.com
                    external_uid: 0396a8f6-37d5-4386-bb63-86987ac88132
                    client_verified: false
                    kyc_status: null
                    lock_reason: null
                    locked_at: null
                    pool_uids:
                    - 1rNd8vRVa4GX84vi
                    primary_customer_uid: null
                    program_uid: Sw9DjTGJq5L1ctZN
                    secondary_customer_uids: []
                    status: initiated
                    total_balance: '0'
                    uid: uKxmLxUEiSj5h4M3
                    archived_at: null
      operationId: postCustomers
      x-operation-id-source: derived
  /customers/{uid}:
    parameters:
    - $ref: '#/paths/~1auth/parameters/0'
    - $ref: '#/paths/~1pools~1%7Buid%7D/parameters/1'
    get:
      tags:
      - Customers
      summary: Get a single Customer
      description: Retrieve overall status about a Customer as well as their total Asset Balances across all accounts.
      responses:
        '200':
          description: A single Customer is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1customers/post/responses/201/content/application~1json/schema'
      operationId: getCustomersByUid
      x-operation-id-source: derived
    put:
      tags:
      - Customers
      summary: Adjust Customer Data
      description: 'Submit or update a Customer''s personally identifiable information (PII) after the Customer is created. Before a Customer has been onboarded to a product with Customer Product, this endpoint may be used to update or remove any details without validations. After the Customer has been onboarded to a product, all validations will be enforced.


        This endpoint is used to supply the remaining personally identifiable information (PII) for each Customer after they are created. The PII for a Customer must be submitted in full. Newline will not accept your request if any field is incomplete or missing.


        PII can be edited for a Customer up until a valid request is sent to the Customer Product endpoint. Once a Customer is in a status of Active, subsequent calls to this endpoint will result in additional KYC/AML evaluations. Each KYC/AML evaluation will result in a billable event for your Program. Please work with Newline on how you plan to implement PII modifications for your Customers.


        Only first_name, middle_name, last_name, suffix, email, phone, and address will be editable after a Customer is in a status of Active. Once Customer data is adjusted, the pii_confirmed_at field on the Customer record will be updated.


        Newline accepts Tax Identifier Number in the Social Security Number field of the API. Newline performs validation on the SSN field supplied with a Customer to prevent invalid SSN values. Newline will reject a Customer record with a SSN value that does not adhere to the following parameters:


        - The 1st part, 3-digits, may not include 000, 666

        - The 2nd part, 2-digits, may range from 01 to 99

        - The 3rd part, 4-digits, may range from 0001 to 9999


        We will accept SSN and TIN in the SSN field of the /customers endpoint.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                external_uid:
                  type:
                  - string
                  - 'null'
                  description: 'An optional Customer identifier supplied by the Partner. If supplied, must be unique among the collection of all Partner''s Customers.

                    '
                  example: partner-generated-id
                email:
                  type:
                  - string
                  - 'null'
                  description: Email of the Customer
                  example: olive.oyl@newline53.com
                details:
                  allOf:
                  - allOf:
                    - allOf:
                      - type: object
                        description: An object containing the supplied identifying information for the Customer
                        properties:
                          first_name:
                            type:
                            - string
                            - 'null'
                            description: 1-40 characters
                            example: Olive
                          middle_name:
                            type:
                            - string
                            - 'null'
                            description: 1-40 characters
                            example: Olivia
                          last_name:
                            type:
                            - string
                            - 'null'
                            description: 1-40 characters
                            example: Oyl
                          suffix:
                            type:
                            - string
                            - 'null'
                            description: 1-30 characters
                            example: Jr.
                      - type: object
                        properties:
                          phone:
                            type:
                            - string
                            - 'null'
                            example: '5555551212'
                            description: Exactly 10 digits long (no hyphens, parentheses, or spaces)
                            pattern: ^\d{10}$
                    - type: object
                      description: An object containing the supplied identifying information for the Customer
                      properties:
                        business_name:
                          type:
                          - string
                          - 'null'
                          description: Required for customers of type `sole_proprietor` and discarded otherwise. 1-256 alphanumeric characters.
                          example: Oliver's Olive Emporium
                  - type: object
                    properties:
                      ssn:
                        type:
                        - string
                        - 'null'
                        writeOnly: true
                        example: 111-22-3333
                        description: Follows pattern 'ddd-dd-dddd'. Required for `primary` or `sole_proprietor` customers.
                        pattern: ^\d{3}-\d{2}-\d{4}$
                      ssn_last_four:
                        type:
                        - string
                        - 'null'
                        readOnly: true
                        example: '3333'
                      dob:
                        type:
                        - string
                        - 'null'
                        format: date
                        description: Follows pattern 'YYYY-MM-DD'
                        example: '1919-12-08'
                      address:
                        type: object
                        properties:
                          street1:
                            type:
                            - string
                            - 'null'
                            description: Maximum 35 characters
                            maxLength: 35
                            example: 123 Abc St.
                          street2:
                            type:
                            - string
                            - 'null'
                            description: Maximum 35 characters
                            maxLength: 35
                            example: Suite 4A
                          city:
                            type:
                            - string
                            - 'null'
                            description: Maximum 35 characters
                            maxLength: 35
                            example: Chicago
                          state:
                            type:
                            - string
                            - 'null'
                            description: 2 characters. Must be a valid US state abbreviation.
                            pattern: ^\w{2}$
                            example: IL
                          postal_code:
                            type:
                            - string
                            - 'null'
                            description: 5-digit string. ZIP+4 is allowed.
                            pattern: ^\d{5}(-\d{4})?$
                            example: '60301'
                        required:
                        - street1
                        - city
                        - state
                        - postal_code
      responses:
        '200':
          description: The updated Customer resource is returned
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1customers/post/responses/201/content/application~1json/schema'
      operationId: putCustomersByUid
      x-operation-id-source: derived
    delete:
      parameters:
      - $ref: '#/paths/~1auth/parameters/0'
      tags:
      - Customers
      summary: Archive a Customer
      description: 'Archiving a Customer refunds any remaining balance, closes all of their active Synthetic and Custodial Accounts and closes their Debit Cards. This process can take up to 8 business days to complete as the Transfers take place.


        When archiving a customer, you can prevent them from reapplying to your program by setting `can_apply_again` to false. If you do not set any value, `can_apply_again` defaults to true.


        When a request to archive a Customer is first received, the customer status will update to `pending_archival` and their accounts will be locked. When the archival process is complete, their customer status will update to `archived`. For a customer to move to the `archived` status, they must carry a $0 balance and have no pending transactions.


        If the Customer has a positive balance across any accounts and a connected external account, Newline will initiate an ACH transfer to zero out the account balance and move the customer to the `archived` status.


        If the Customer does not have an external account or the ACH transfer fails, Newline will mail a paper check to the Customer address on file to zero out the account balance and move the customer to the `archived` status.


        If the Customer has a negative balance across any accounts, the negative account balances must be brought up to or greater than $0.00 before the archival workflow can continue.


        Once archived, a Customer''s records will still be available for historical purposes (according to the bank’s record retention schedule), but they will not be able to open any new Accounts. The Customer can still apply again as long as `can_apply_again` is not set to false.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                archive_note:
                  type:
                  - string
                  - 'null'
                  example: for inactivity
                can_apply_again:
                  type:
                  - boolean
                  - 'null'
                  default: true
                destination_synthetic_account_uid:
                  type: string
                  description: 'UID of an active external Synthetic Account to which the Customer''s funds should be sent, if any. Required if the Customer has multiple active external Synthetic Accounts.

                    '
                  example: oBASVwLQB4RojU5X
      responses:
        '200':
          description: Customer has begun the archive process.
          headers:
            x-trace-id:
              $ref: '#/paths/~1auth/post/responses/201/headers/x-trace-id'
          content:
            application/json:
              schema:
                $ref: '#/paths/~1customers/post/responses/201/content/application~1json/schema'
      operationId: deleteCustomersByUid
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Access token signed with shared HMAC
x-explorer-enabled: false
